# Generated by Django 4.1 on 2022-09-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
