# Generated by Django 4.1 on 2022-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='keeptrack/images/'),
        ),
    ]
