# Generated by Django 4.1 on 2022-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coin',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
