# Generated by Django 4.1 on 2022-09-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_inbox_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at']},
        ),
    ]
