# Generated by Django 4.1 on 2022-09-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_message_options'),
        ('note', '0003_alter_featurednote_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmark',
            new_name='BookmarkedNote',
        ),
    ]
