# Generated by Django 4.1 on 2022-09-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_rename_bookmark_bookmarkednote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurednote',
            name='note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='note.note'),
        ),
    ]
