# Generated by Django 4.1 on 2022-09-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_link', models.URLField(blank=True, max_length=500, null=True)),
                ('code_link', models.URLField(blank=True, max_length=500, null=True)),
                ('project_state', models.BooleanField(default=False)),
            ],
        ),
    ]
