# Generated by Django 4.1 on 2022-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='images/undraw_projections_re_ulc6.svg', null=True, upload_to='keeptrack/images/'),
        ),
    ]
