# Generated by Django 4.1 on 2022-09-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
