# Generated by Django 4.1 on 2022-09-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='object_id',
        ),
        migrations.CreateModel(
            name='SkillObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skill')),
            ],
        ),
    ]
