# Generated by Django 4.1 on 2022-09-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_remove_skill_content_type_remove_skill_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='current_exp',
            new_name='current_point',
        ),
    ]
