# Generated by Django 4.1 on 2022-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_rename_current_exp_skill_current_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='started_learning',
            field=models.DateField(blank=True, null=True),
        ),
    ]
