# Generated by Django 4.1 on 2022-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0005_alter_skill_started_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='started_learning',
            field=models.DateField(blank=True, null=True),
        ),
    ]
