# Generated by Django 4.1 on 2022-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0008_skill_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(default=1),
        ),
    ]
