# Generated by Django 4.1 on 2022-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_alter_skill_skill_type_delete_skilltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('programming_langauge', 'Programming Language'), ('database', 'Database'), ('hosting_platform', 'Hosting Platform'), ('coding_utility', 'Coding Utility'), ('frontend_framework', 'Frontend Framework'), ('backend_framework', 'Backend Framework'), ('machine_learning', 'Machine Learning'), ('data_science', 'Data Science'), ('artificial_intelligence', 'Artificial Intelligence')], max_length=200, null=True),
        ),
    ]
