# Generated by Django 4.1 on 2022-09-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_message_options'),
        ('skill', '0013_alter_skill_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(blank=True, default='Coding Utility', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(blank=True, choices=[('Programming Language', 'Programming Language'), ('Database', 'Database'), ('Hosting Platform', 'Hosting Platform'), ('Coding Utility', 'Coding Utility'), ('Frontend Framework', 'Frontend Framework'), ('Backend Framework', 'Backend Framework'), ('Machine Learning Tool', 'Machine Learning Tool'), ('Data Science Tool', 'Data Science Tool'), ('Artificial Intelligence Tool', 'Artificial Intelligence Tool')], max_length=200, null=True),
        ),
    ]
