# Generated by Django 4.1 on 2022-09-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_alter_skill_owner_alter_skill_skill_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_level', 'current_point']},
        ),
    ]
