# Generated by Django 4.1 on 2022-09-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-skill_level', '-current_point']},
        ),
    ]
